nomes = ["Deyverson", "Caça Rato", "Neymar", "Dorival", "Bolsonaro", "Gabigol", "Breno Lopes"]
print(nomes)
nomes.reverse()
print(nomes.index("Neymar"))
nomes.remove("Neymar")
print(nomes)
nomes.pop(3)
print(nomes)
nomes.append("Bolsonaro")
nomes.append("Bolsonaro")
nomes.append("Bolsonaro")
nomes.append("Bolsonaro")
print(nomes)
print(nomes.count("Bolsonaro"))
print(sorted())
numeros = [3, 1, 6, 4, 9, 0, 123, 321, 456, 3245]
print(min(numeros))
print(max(numeros))
print(sum(numeros))